services:
  orthanc1:
    build:
      dockerfile: tests/orthanc/orthanc-for-test.Dockerfile
      context: .
    environment:
      PYTHON_PLUGIN_ENABLE: "true"
      ORTHANC__PYTHON_SCRIPT: "/python/script.py"
    depends_on:
      - orthanc2
  orthanc2:
    image: orthancteam/orthanc:24.5.1
  test:
    build:
      context: .
      dockerfile: tests/orthanc/pytest.Dockerfile
    depends_on:
      - orthanc1
      - orthanc2
